### ISSUE TITLE
motion_workflow.delete

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#48]

**Comment by FinnStutzenstein** [comment]
- If the workflow is linked as a default one, this error has to be improved: `Cannot delete a default workflow.` Maybe something like `The workflow is set as the default workflow for ...`.

- If I want to delete a workflow, which is not set as any default, I get:

```
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
backend_1           |     self.handle_request(listener, req, client, addr)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
backend_1           |     respiter = self.wsgi(environ, resp.start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 128, in __call__
backend_1           |     return self.wsgi_application(environ, start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 118, in wsgi_application
backend_1           |     response = self.dispatch_request(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 49, in dispatch_request
backend_1           |     return self.default_route(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 74, in default_route
backend_1           |     response_body, access_token = view_instance.dispatch(
backend_1           |   File "/app/openslides_backend/http/views.py", line 73, in dispatch
backend_1           |     result = handler.handle_request(payload, user_id)
backend_1           |   File "/app/openslides_backend/action/action.py", line 77, in handle_request
backend_1           |     write_request_element = self.parse_actions(payload)
backend_1           |   File "/app/openslides_backend/action/action.py", line 116, in parse_actions
backend_1           |     write_request_elements = action(self.permission, self.database).perform(
backend_1           |   File "/app/openslides_backend/action/base.py", line 84, in perform
backend_1           |     dataset = self.prepare_dataset(payload)
backend_1           |   File "/app/openslides_backend/action/generics.py", line 305, in prepare_dataset
backend_1           |     return self.delete_action_prepare_dataset(payload)
backend_1           |   File "/app/openslides_backend/action/generics.py", line 420, in delete_action_prepare_dataset
backend_1           |     delete_action.perform(payload, self.user_id)
backend_1           |   File "/app/openslides_backend/action/base.py", line 84, in perform
backend_1           |     dataset = self.prepare_dataset(payload)
backend_1           |   File "/app/openslides_backend/action/generics.py", line 305, in prepare_dataset
backend_1           |     return self.delete_action_prepare_dataset(payload)
backend_1           |   File "/app/openslides_backend/action/generics.py", line 424, in delete_action_prepare_dataset
backend_1           |     relations = self.get_relations(
backend_1           |   File "/app/openslides_backend/action/base.py", line 347, in get_relations
backend_1           |     result = handler.perform()
backend_1           |   File "/app/openslides_backend/action/relations.py", line 202, in perform
backend_1           |     return self.prepare_result_to_id(add, remove, rels, related_name)
backend_1           |   File "/app/openslides_backend/action/relations.py", line 403, in prepare_result_to_id
backend_1           |     new_value = rel[related_name]
backend_1           | KeyError: 'previous_state_ids'
```

I'm not really sure, if this is directly reproduceable since I change too much in the db at this point; But: It has a fresh created state (possibly not many fields set there), and one motion is in a state of this workflow.

**Comment by jsangmeister** [comment]
@normanjaeckel can you look into this?

**Comment by normanjaeckel** [comment]
I found a bug concerning workflow deletion but it is not the same. Can someone write a reproducable backend test case for this bug here? See https://github.com/OpenSlides/openslides-backend/pull/300/ how to do this.

**Comment by jsangmeister** [comment]
@normanjaeckel you did implement this test as well in https://github.com/OpenSlides/openslides-backend/pull/300, didn't you? Then this should also be fixed with it

**Comment by normanjaeckel** [comment]
I am not sure whether this was the same case. After https://github.com/OpenSlides/openslides-backend/pull/300 is merged the client devs should check again.

**Comment by jsangmeister** [comment]
Merged. Please re-check

**Comment by jsangmeister** [comment]
ping
