### ISSUE TITLE
topic.delete

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend-coordination#82]

**Comment by jsangmeister** [comment]
@GabrielInTheWorld ping

**Comment by FinnStutzenstein** [comment]
Still throws the error (Same as above and in #48) on the current master. I deleted some topics successfully, but after 2 it just give this error, so I'm not sure what exactly triggers the error.

```
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
backend_1           |     self.handle_request(listener, req, client, addr)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
backend_1           |     respiter = self.wsgi(environ, resp.start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 128, in __call__
backend_1           |     return self.wsgi_application(environ, start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 118, in wsgi_application
backend_1           |     response = self.dispatch_request(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 49, in dispatch_request
backend_1           |     return self.default_route(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 74, in default_route
backend_1           |     response_body, access_token = view_instance.dispatch(
backend_1           |   File "/app/openslides_backend/http/views.py", line 73, in dispatch
backend_1           |     result = handler.handle_request(payload, user_id)
backend_1           |   File "/app/openslides_backend/action/action.py", line 77, in handle_request
backend_1           |     write_request_element = self.parse_actions(payload)
backend_1           |   File "/app/openslides_backend/action/action.py", line 116, in parse_actions
backend_1           |     write_request_elements = action(self.permission, self.database).perform(
backend_1           |   File "/app/openslides_backend/action/base.py", line 84, in perform
backend_1           |     dataset = self.prepare_dataset(payload)
backend_1           |   File "/app/openslides_backend/action/generics.py", line 305, in prepare_dataset
backend_1           |     return self.delete_action_prepare_dataset(payload)
backend_1           |   File "/app/openslides_backend/action/generics.py", line 420, in delete_action_prepare_dataset
backend_1           |     delete_action.perform(payload, self.user_id)
backend_1           |   File "/app/openslides_backend/action/base.py", line 84, in perform
backend_1           |     dataset = self.prepare_dataset(payload)
backend_1           |   File "/app/openslides_backend/action/generics.py", line 305, in prepare_dataset
backend_1           |     return self.delete_action_prepare_dataset(payload)
backend_1           |   File "/app/openslides_backend/action/generics.py", line 420, in delete_action_prepare_dataset
backend_1           |     delete_action.perform(payload, self.user_id)
backend_1           |   File "/app/openslides_backend/action/base.py", line 84, in perform
backend_1           |     dataset = self.prepare_dataset(payload)
backend_1           |   File "/app/openslides_backend/action/generics.py", line 305, in prepare_dataset
backend_1           |     return self.delete_action_prepare_dataset(payload)
backend_1           |   File "/app/openslides_backend/action/generics.py", line 424, in delete_action_prepare_dataset
backend_1           |     relations = self.get_relations(
backend_1           |   File "/app/openslides_backend/action/base.py", line 347, in get_relations
backend_1           |     result = handler.perform()
backend_1           |   File "/app/openslides_backend/action/relations.py", line 202, in perform
backend_1           |     return self.prepare_result_to_id(add, remove, rels, related_name)
backend_1           |   File "/app/openslides_backend/action/relations.py", line 403, in prepare_result_to_id
backend_1           |     new_value = rel[related_name]
backend_1           | KeyError: 'speaker_ids'
```

**Comment by jsangmeister** [comment]
@normanjaeckel can you look into this?

**Comment by normanjaeckel** [comment]
Please help me: How can I add example data to the running datastore container after I started everything with `make run-bash` from backend Makefile.

**Comment by FinnStutzenstein** [comment]
In the main repo there are helper scripts to manipulate the DS: https://github.com/OpenSlides/OpenSlides/tree/openslides4-dev/dev-commands

Since they depend on the docker setup you might have to copy them and manipulate for your needs. Also: These commands require the DS to be in development mode (ste the env DATASTORE_ENABLE_DEV_ENVIRONMENT=1) and have ports exposed.

**Comment by FinnStutzenstein** [comment]
@jsangmeister ./clear and ./export (except for the meta fields) can be done with a single curl statement, but importing not. Maybe thsi should also get a dev-only route...

**Comment by normanjaeckel** [comment]
So which is the commend to import the example data you ask me to test?

**Comment by FinnStutzenstein** [comment]
In the dev setup, you can do `./export-ds.sh`, modify the `export.json` and import it again `./set-ds.sh export.json`. This needs to be adapted into your repository to have it available in your dev setup.

**Comment by normanjaeckel** [comment]
I can not reproduce it. Please provide a test to me if this problem still appears.

**Comment by FinnStutzenstein** [comment]
Ok, I reproduced it on the first try with fresh example data: I started the complete setup, logged in, go to topic 1, send
```
[{action: "topic.delete", data: [{id: 1}]}]
```
and got the error above...

**Comment by normanjaeckel** [comment]
Ah if you click "Remove from agenda" the problem does not appear because this is another action (although it should produce the same result).

**Comment by FinnStutzenstein** [comment]
> although it should produce the same result

this should only delete the agenda_item, not the topic (this should not be possible: It might be a bug in the UI, but must be ensured in the backend). When deleting a topic, both are deleted.

**Comment by normanjaeckel** [comment]
Why not deleting agenda item and topic together with an agenda_item.delete call?

**Comment by FinnStutzenstein** [comment]
I think it is irrelevant - every case is a special treatment: Either do not allow for topics or topics is the only object that is cascade-deleted.

**Comment by jsangmeister** [comment]
The error should be fixed now, please check.
